### ISSUE TITLE
Test failed on Ubuntu Xenial 4.4 after commit 1fc2eec2

### ISSUE THREAD

**Issue by Cypresslin** [amir73il/unionmount-testsuite#4]
Hello,

while we're running our kernel SRU regression test, we found that this test suite will fail on Ubuntu Xenial 4.4.0-186-generic with the following error message:

> Running './run --ov'
> /mnt/a/foo100: File unexpectedly on lower fs
> Environment variables:
> \*\*\*
> *** ./run --ov --ts=0 open-plain
> \*\*\*
> TEST open-plain.py:10: Open O_RDONLY

If reset the HEAD commit to 1fc2eec2 the test will pass. 

(With 2104e51d the test will fail with /mnt/a/foo100: File unexpectedly on upper layer)

Looks like it works with 4.15 kernel on Xenial.
Do you know if we're missing any kernel commit for this issue?
Thank you.

**Comment by amir73il** [comment]
Thank you for the report.

There have been a lot of changes in the kernel since v4.4 related to the exposed overlay st_dev and the test has been adapted to check the upstream behavior. For example commit dc24a45 "Update layer check with pseudo st_dev for upper layer"
but it is not the only one.

Some behaviors of newer kernels (e.g. constant st_ino) are checked only with test option --verify.
I think the simplest thing to do is to relax this specific error when --verify is not specified.
I pushed commit 019085f "Relax layers check for older kernels" to branch overlayfs-devel.
Please verify that is works for you and I will merge it.

**Comment by Cypresslin** [comment]
Hello Amir,

thanks for your quick fix, I have this branch tested on Ubuntu Xenial 4.4 and it's not failing anymore, you will find the detailed test report in the following link.
https://pastebin.ubuntu.com/p/B8bHqfwYwS/

Thank you!
PHLin
